apiVersion: v1
kind: Service
metadata:
  name: fastapi-boilerplate-service
  namespace: fastapi-boilerplate
  labels:
    app: fastapi-boilerplate
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: fastapi-boilerplate
  sessionAffinity: None

